/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_lunalux_libos_Window */

#ifndef _Included_uk_co_lunalux_libos_Window
#define _Included_uk_co_lunalux_libos_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    createWindow
 * Signature: (Luk/co/lunalux/libos/Window/windowInfo;)Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_createWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    createKeyboard
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_createKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    createMouse
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_createMouse
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    createTouch
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_createTouch
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    losUpdateWindow
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_losUpdateWindow
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    isKeyDown
 * Signature: (Luk/co/lunalux/libos/Window/keyboardButton;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_isKeyDown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    isMouseDown
 * Signature: (Luk/co/lunalux/libos/Window/mouseButton;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_isMouseDown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    requestClose
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_requestClose
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    requestMousePosition
 * Signature: ()Luk/co/lunalux/libos/Window/position;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_requestMousePosition
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    requestMouseWheelDelta
 * Signature: ()Luk/co/lunalux/libos/Window/position;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_requestMouseWheelDelta
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    isBeingPressed
 * Signature: ()Luk/co/lunalux/libos/Window/position;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_isBeingPressed
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    destroyKeyboard
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_destroyKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    destroyMouse
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_destroyMouse
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    destroyTouch
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_destroyTouch
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_Window
 * Method:    destroyWindow
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_Window_destroyWindow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
