/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_lunalux_libos_NetIO */

#ifndef _Included_uk_co_lunalux_libos_NetIO
#define _Included_uk_co_lunalux_libos_NetIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_lunalux_libos_NetIO
 * Method:    losNetworkBytesToSystemBytes
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_NetIO_losNetworkBytesToSystemBytes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_lunalux_libos_NetIO
 * Method:    losSystemBytesToNetworkBytes
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_NetIO_losSystemBytesToNetworkBytes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_lunalux_libos_NetIO
 * Method:    losCreateSocket
 * Signature: (Luk/co/lunalux/libos/NetIO/createSocketInfo;)Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_NetIO_losCreateSocket
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_lunalux_libos_NetIO
 * Method:    losReadSocket
 * Signature: ()Luk/co/lunalux/libos/NetIO/socketResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_NetIO_losReadSocket
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_lunalux_libos_NetIO
 * Method:    losWriteSocket
 * Signature: (Ljava/lang/String;)Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_NetIO_losWriteSocket
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_lunalux_libos_NetIO
 * Method:    losDestroySocket
 * Signature: ()Luk/co/lunalux/libos/Defines/losResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_lunalux_libos_NetIO_losDestroySocket
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
